name: "First Custom Action Workflow"
on:
    push
jobs:
    custom-action-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Run Custom Action
              uses: ./.github/actions/hello-world      