name: My First Workflow
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello, World!"
      - name: Step 2
        run: echo "Hello, World! From Step 2"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello, World! final step - job -2 "