name: "Action to build Java project and return build output"
description: "This action builds a Java project using Maven and returns the build output."
inputs:
    java-version:
        description: "Specify the Java version to use (e.g., 8, 11, 17)"
        type: string
        required: false
        default: "21"
outputs:
    jar_file:
        description: "The path to the built JAR file."
runs:
    using: "composite"
    steps:
        - name: "Checkout repository"
          uses: actions/checkout@v4

        - name: "Set up Java"
          uses: actions/setup-java@v3 
          with:
            distribution: "temurin"
            java-version: ${{ inputs.java-version }}

        - name: Give Maven Wrapper Permission
          shell: bash
          run: chmod +x CICDDEMO/mvnw
        - name: Build Spring Boot Application
          shell: bash
          run: |
            cd CICDDEMO
            ./mvnw clean package -DskipTests
        - name: Return Build Output
          shell: bash
          run: |
            Jar_File=$(find ./CICDDEMO/target -name "*.jar" -f | head -n 1)
            echo "Build output JAR file: $Jar_File"
            echo "jar_file: $Jar_File" >> $GITHUB_OUTPUT