name: "The First Input workflow"
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "The Environment to deploy too"
                required: true
                type: string
jobs:
    manually-input-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print the Input Value
              run: |
                 echo "The Input Value is: ${{ inputs.environment }}" 
                                