name: 01 - First Workflow to Demostrate Environment Creation Purposes
on:
    push:
        branches:
            - main
            - feature/*
            - develop
env:
    APPLICATION_NAME: cicddemo            
jobs:
        
    develop-dev-job:
        name: Deploy to Development
        if: github.ref_name=='develop'
        runs-on: ubuntu-latest
        environment: dev
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: '21'
                cache: maven

            - name: Verify Java and Maven
              working-directory: ./CICDDEMO
              run: |
                java -version
                javac -version
            - name: Display Branch Informatio
              run: |
                echo "Branch: ${{github.ref_name}}"

            - name: Display Environment Information
              run: |
                echo "Application URL : ${{vars.APP_URL}}"
                echo "Application Debug_Mode : ${{vars.DEBUG_MODE}}"    


  # 2. Build Spring Boot application
            - name: Build Spring Boot Application
              working-directory: ./CICDDEMO
              run: |
                chmod +x mvnw
                ./mvnw clean package -DskipTests

  # 3. Generate a unique image tag
            - name: Generate Dynamic Image Tag
              run: |
                echo "IMAGE_TAG=v${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}" >> $GITHUB_ENV

  # 4. Display information
            - name: Display Build Information
              run: |
                echo "Application: $APPLICATION_NAME"
                echo "Repository: $GITHUB_REPOSITORY"
                echo "Actor: $GITHUB_ACTOR"
                echo "Branch: $GITHUB_REF_NAME"
                echo "Image Tag: $IMAGE_TAG"



  # 5. Login to GitHub Container Registry
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

  # 6. Build Docker image
            - name: Build Docker Image
              uses: docker/build-push-action@v7
              with:
                context: ./CICDDEMO
                push: false
                tags: ghcr.io/${{ github.repository_owner }}/${{ env.APPLICATION_NAME }}:${{ env.IMAGE_TAG }}

  # 7. Run container
            - name: Run Container
              run: |
                docker run -d \
                -p 8080:8080 \
                --name cicddemo-container \
                ghcr.io/${{ github.repository_owner }}/${{ env.APPLICATION_NAME }}:${{ env.IMAGE_TAG }}

  # 8. Smoke test
            - name: Smoke Test Application
              run: |
                sleep 25
                curl --fail http://localhost:8080/get/taha

  # 9. Push image to GHCR
            - name: Push Docker Image to GHCR
              if: ${{ success() }}
              run: |
                docker push ghcr.io/${{ github.repository_owner }}/${{ env.APPLICATION_NAME }}:${{ env.IMAGE_TAG }}

  # 10. Collect logs if something fails
            - name: Collect Container Logs
              if: ${{ failure() }}
              run: |
                docker logs cicddemo-container

  # 11. Cleanup
            - name: Cleanup Container
              if: ${{ always() }}
              run: |
                docker rm -f cicddemo-container || true
              
    develop-prod-job:
        name: Deploy to Development
        
        runs-on: ubuntu-latest
        environment: prod

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: '21'
                cache: maven

            - name: Verify Java and Maven
              working-directory: ./CICDDEMO
              run: |
                java -version
                javac -version
            - name: Display Branch Informatio
              run: |
                echo "Branch: ${{github.ref_name}}"

            - name: Display Environment Information
              run: |
                echo "Application URL : ${{vars.APP_URL}}"
                echo "Application Debug_Mode : ${{vars.DEBUG_MODE}}"    


  # 2. Build Spring Boot application
            - name: Build Spring Boot Application
              working-directory: ./CICDDEMO
              run: |
                chmod +x mvnw
                ./mvnw clean package -DskipTests

  # 3. Generate a unique image tag
            - name: Generate Dynamic Image Tag
              run: |
                echo "IMAGE_TAG=v${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}" >> $GITHUB_ENV

  # 4. Display information
            - name: Display Build Information
              run: |
                echo "Application: $APPLICATION_NAME"
                echo "Repository: $GITHUB_REPOSITORY"
                echo "Actor: $GITHUB_ACTOR"
                echo "Branch: $GITHUB_REF_NAME"
                echo "Image Tag: $IMAGE_TAG"



  # 5. Login to GitHub Container Registry
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

  # 6. Build Docker image
            - name: Build Docker Image
              uses: docker/build-push-action@v7
              with:
                context: ./CICDDEMO
                push: false
                tags: ghcr.io/${{ github.repository_owner }}/${{ env.APPLICATION_NAME }}:${{ env.IMAGE_TAG }}

  # 7. Run container
            - name: Run Container
              run: |
                docker run -d \
                -p 8080:8080 \
                --name cicddemo-container \
                ghcr.io/${{ github.repository_owner }}/${{ env.APPLICATION_NAME }}:${{ env.IMAGE_TAG }}

  # 8. Smoke test
            - name: Smoke Test Application
              run: |
                sleep 25
                curl --fail http://localhost:8080/get/taha

  # 9. Push image to GHCR
            - name: Push Docker Image to GHCR
              if: ${{ success() }}
              run: |
                docker push ghcr.io/${{ github.repository_owner }}/${{ env.APPLICATION_NAME }}:${{ env.IMAGE_TAG }}

  # 10. Collect logs if something fails
            - name: Collect Container Logs
              if: ${{ failure() }}
              run: |
                docker logs cicddemo-container

  # 11. Cleanup
            - name: Cleanup Container
              if: ${{ always() }}
              run: |
                docker rm -f cicddemo-container || true
              
