name: 01-03 SpringBoot CI Workflow

on: push

jobs:
    springboot-ci-job:
        runs-on: ubuntu-latest

        steps:
            - name: CheckOutRepository
              uses: actions/checkout@v7

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
            - name: Give Maven Wrapper Permission
              run: chmod +x CICDDEMO/mvnw
            - name: Build Spring Boot Application
              run: |
                  cd CICDDEMO
                  ./mvnw clean package -DskipTests

            - name: Build Docker Image
              run: docker build -t githubaction-springboot-app:v1 ./CICDDEMO

            - name: Run Container  
              run: docker run -d -p 8082:8080 --name githubaction-springboot-container githubaction-springboot-app:v1
 
            - name: Check Container Status
              run: docker ps -a
 
            - name: Smoke Test
              run: |
                  sleep 10
                  echo "===== CONTAINER LOGS ====="
                  docker logs githubaction-springboot-container
                  echo "===== CURL TEST ====="
                  curl -v http://localhost:8082/get/taha > smoke-test-report.txt 2>&1
            - name: Docker Logs
              run: |
                  echo logs githubaction-springboot-app:v1 > Container-logs.txt 2>&1

            - name: Upload Artifacts
              uses: actions/upload-artifact@v7
              with:
                  name: springboot-app-artifacts
                  path: | 
                      smoke-test-report.txt
                      Container-logs.txt

    review-job:
        runs-on: ubuntu-latest
        needs: springboot-ci-job
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v8
              with:
                name: springboot-app-artifacts
            - name: Consume Artifacts
              run: |
                  echo "Smoke Test Report is this"
                  cat smoke-test-report.txt
                  echo "Container-logs are this"
                  cat Container-logs.txt