name: "Boolean Input workflow to demonstrate the purpose of boolean"
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Please Choose Your Environment"
                required: true
                type: boolean
jobs:
    Boolean-Input:
        runs-on: ubuntu-latest
        steps:
            - name: Checking the Boolean Value
              if: ${{ inputs.environment}}
              run: echo "You have selected True for the environment input."
