name: "practing workflow other essentials"
on:
    workflow_dispatch:
        inputs:
            version:
                description: "please enter your version number"
                required: true
                type: string
job:
    env-input:
        env:
            version: ${{inputs.version}}
            runs-on: ubuntu-latest    
            steps:
                - name: Checking the Environment Variable
                                    run: echo "The version number you entered is $version"