name: "Fourth Custom Action Workflow without predefined actions"
on:
    workflow_dispatch:
        inputs:
            java-version:
                description: "Please enter java version"
                type: string
                required: false
            maven-version:
                description: "Please enter maven version"
                type: string
                required: false
jobs:
    custom-action-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: ./.github/actions/hello-world      
              with:
                java-version: ${{ inputs.java-version }}
                mvn-version: ${{ inputs.maven-version }}                
