name: "Caller Workflow to demonstrate the purpose of reusable workflow"
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Please Choose Your Environment"
                required: true
                type: string
jobs:
    caller-worflow:
        uses: ./.github/workflows/05-05-reusable-workflows-ci.yml
        with:
            environment: ${{ inputs.environment }}